### ISSUE TITLE
Include workaround for AudioContext requiring interaction

### ISSUE THREAD

**Issue by hymm** [bevyengine/bevy_github_ci_template#17]
Should the template include this workaround for AudioContexts?

https://developer.chrome.com/blog/web-audio-autoplay/#moving-forward

I think itch.io does something for this already, but it's fixes some issues with sounds not playing when running on other web pages.

**Comment by mockersf** [comment]
Ooh, good find!

What happens if we add this when deploying on itch.io?

**Comment by hymm** [comment]
> What happens if we add this when deploying on itch.io?

I think it should be fine. I deployed to itch.io in the past with a similar workaround I took from https://github.com/NiklasEi/bevy_game_template.

**Comment by rparrett** [comment]
I also use this workaround on itch.

It is necessary when using the ```Automatically start on page load``` option and should be harmless otherwise.
