### ISSUE TITLE
Release action failing at Step "Prepare Package" for Windows, Linux and MacOs

### ISSUE THREAD

**Issue by zwazel** [bevyengine/bevy_github_ci_template#24]
Hello :)

I'm experiencing some issues with the Release action. 
I removed the WASM export and kept the itch.io export disabled.
the other three, windows, linux and macos, work fine until they get to the "Prepare Package" step. There all of them are failing.

I'm using bevy 0.9.1 right now. Everything has been directly copied from this template, the only two things i changed were
- removing wasm
- edited the binary env to my binary name.

The CI from this template works without issues.

Images below with the errors.

![image](https://user-images.githubusercontent.com/42088586/224502789-f72b1e4b-5b8a-4185-a036-8346aaa16c19.png)
![image](https://user-images.githubusercontent.com/42088586/224502797-1b9c9449-84d7-4ef5-8f96-db7a21f4144c.png)
![image](https://user-images.githubusercontent.com/42088586/224502802-7dc077f8-1f71-451d-be4e-598ef09d437a.png)

**Comment by mockersf** [comment]
The name you set in the `binary` env variable must match the name of an executable built by your package

**Comment by zwazel** [comment]
okay, yea my bad. I was looking at this repo and thought it only had to be the name of the project that is defined in the cargo.toml. stupid mistake from me. It's solved now.
