### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by NiklasEi** [bevyengine/bevy_github_ci_template#4]
Shouldn't the template be licensed in a way that allows the user to start from this code and later publish it under any license they want?

The current license is copy-paste from the engine repository. It points to dual MIT/Apache 2 with two dead links.

**Comment by cart** [comment]
I'm open to alternative licenses. Most of the "zero attribution or restriction" licenses im aware of are pretty niche. Might be worth looking in to what licenses are popular for templates. @mockersf you put together this project. Are you open to relicensing and if so, do you have any thoughts on a what a good one would be?

**Comment by mockersf** [comment]
no opposition from me to relicensing!

**Comment by NiklasEi** [comment]
I do understand correctly, that if I start using this template it's not possible to just change the license? In that case we would be forcing MIT/Apache on the user's game here.

**Comment by mockersf** [comment]
I guess you're right. But if someone cares for license, we can't leave the template itself without one. Maybe a written permission in the template to relicense as the user want? Or license the template in a more permissive way?
Then, how can we stop this more permissive license to be applied to the user code? When the template is applied, every file is copied, there's no difference between template files and final project file...
Also, I don't think that being Apache2/MIT doesn't stop from being closed source. As the license owner is the user (once we solve the fact that there is code owned by the template), they just have to not sue themselves

**Comment by benfrankel** [comment]
This issue can be closed as completed?
