### ISSUE TITLE
Bevy Logo License issue

### ISSUE THREAD

**Issue by DGriffin91** [bevyengine/bevy_github_ci_template#45]
The addition of the CC0 license in https://github.com/bevyengine/bevy_github_ci_template/pull/42 implies that the bevy logo is CC0, but it is not.
From @cart:
> I retain all rights to the logo atm. The license section explicitly calls out that the code is dual licensed under mit/apache.

https://discord.com/channels/691052431525675048/745355529777315850/995411630563262519

I think either the logo or the CC0 license needs to be removed from the template.

I would prefer the CC0 license removed personally as I think it creates a high possibility that people using this template will either include assets that are somewhat permissively licensed, but not CC0 and forget to remove the license, or they don't intend for their personal assets to be licensed this way.

**Comment by ickk** [comment]
I think the CC0 license itself is very appropriate for this kind of repository. We want users of this template to completely own the copyright to whatever game they make with it.

That said, ideally the licenses themselves wouldn't be necessarily be included in the copy of the template that a user gets however, as they may not think to remove them when required.

As a workaround, we could keep the license text somewhere external to the source code

**Comment by cart** [comment]
Yeah I think the Bevy logo should be removed to avoid confusion.
