### ISSUE TITLE
Disable console on windows for release builds

### ISSUE THREAD

**Issue by benfrankel** [bevyengine/bevy_github_ci_template#55]
See https://github.com/janhohenheim/foxtrot/blob/274563b701a4d2002ff4d585d02d54f56a7704e5/src/main.rs#L1 for an example of this.

**Comment by mockersf** [comment]
goal of this template is "This repo show how to set up CI on a GitHub project for Bevy"

I would prefer to keep it limited to that

**Comment by benfrankel** [comment]
This repo already includes the `AssetMetaCheck::Never` workaround and `#![allow(clippy::too_many_arguments, clippy::type_complexity)]`. So this seems in scope.

**Comment by mockersf** [comment]
`#![allow(clippy::too_many_arguments, clippy::type_complexity)]` is to pass CI, `AssetMetaCheck::Never` is to be able to publish (through CI) to itch.io

**Comment by benfrankel** [comment]
I mean IMO this is required to publish on Windows. But I guess you could argue that having the release build open a console doesn't completely prevent the build from running.
