### ISSUE TITLE
Add credits menu

### ISSUE THREAD

**Issue by janhohenheim** [bevyengine/bevy_github_ci_template#57]
Everyone in the team behind a jam entry should have an easy way to add their name into the game for proper credit.

**Comment by mockersf** [comment]
goal of this template is "This repo show how to set up CI on a GitHub project for Bevy"

I would prefer to keep it limited to that

**Comment by janhohenheim** [comment]
I was told to add these issues as part of the discussion at https://discord.com/channels/691052431525675048/1258521739395203174
