### ISSUE TITLE
Use hack to not get flickering at the start of the game

### ISSUE THREAD

**Issue by janhohenheim** [bevyengine/bevy_github_ci_template#61]
https://github.com/janhohenheim/foxtrot/blob/main/src/bevy_config.rs#L51-L60

**Comment by benfrankel** [comment]
A `Boot` state may be a better way to do this.

**Comment by mockersf** [comment]
goal of this template is "This repo show how to set up CI on a GitHub project for Bevy"

I would prefer to keep it limited to that
