### ISSUE TITLE
Remove GitHub token from Clippy workflow job

### ISSUE THREAD

**Issue by TimJentzsch** [bevyengine/bevy_github_ci_template#9]
This GitHub token reference seems unnecessary:
<https://github.com/bevyengine/bevy_github_ci_template/blob/3e0784af0159b3fe2eb0631d445fb00897c3183e/.github/workflows/ci.yaml#L73>

**Comment by mockersf** [comment]
it is used to post clippy results using the GitHub api in PRs

**Comment by TimJentzsch** [comment]
What do you mean by that? They are left as a comment in the PR?

**Comment by mockersf** [comment]
yup, see the action: https://github.com/actions-rs/clippy-check
